language: csharp
solution: AlgorithmForce.Searching.sln
dist: trusty
mono: none
dotnet: 1.0.1

install:
- dotnet restore

script:
- dotnet build
- dotnet test src/AlgorithmForce.Searching.Test/AlgorithmForce.Searching.Test.csproj
